<a href="https://colab.research.google.com/github/Gilmar-PY/C8280AC2/blob/main/Actividad2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Matrices**                     
Una matriz NumPy es una colección de valores de tipos de datos similares y está indexada por una tupla de números no negativos. El rango de la matriz es el número de dimensiones, y la forma de una matriz es una tupla de números que dan el tamaño de la matriz a lo largo de cada dimensión

In [1]:
# Ejemplo 
from __future__ import division
import time
import numpy as np
tam_vec = 1000
def lista_python():
    t1 = time.time()
    X = range(tam_vec)
    Y = range(tam_vec)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1
def matriz_numpy():
    t1 = time.time()
    X = np.arange(tam_vec)
    Y = np.arange(tam_vec)
    Z = X + Y
    return time.time() - t1
# Completar
import numpy
print(numpy.__version__)



1.22.4


Podemos inicializar matrices NumPy a partir de listas de Python anidadas y acceder a los elementos mediante corchetes.

In [2]:
import numpy as np

# Creamos una matriz 3x3 de todos ceros
a = np.zeros((3,3)) 
print(a)

# Creamos una matriz 2x2 de todos 1
b = np.ones((2,2))  
print(b)

# Creamos una matriz 3x3 constantes
c = np.full((3,3), 7)
print(c)

# Creamos una matriz 3x3 con valores aleatorios
d = np.random.random((3,3)) 
print(d)

# Creamos una matriz identidad 3x3 
e = np.eye(3)
print(e)

# Convertir una lista en una matriz 
f = np.array([2, 3, 1,0])
print(f)

# arange() crea matrices con valores que se incrementan regularmente
g = np.arange(0, 20, 2) # Del 0 al 20 con incremento de 2
print(g)

# Mezcla de tupla y listas
h = np.array([(1.5,2,3), (4,5,6)]) # Crea una matriz de 2x3
print(h)

# Crear una matriz de rango con tipo de datos flotante
i = np.arange(1, 8, dtype=np.float64)
print(i)

# linspace() crea matrices con un numero especifico de elementos que están espaciados por igual entre los valores inicial y final especificados
j = np.linspace(0, 1, num=5) # Genera 5 números igualmente espaciados entre 0 y 1
print(j)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.87599492 0.17936402 0.37915184]
 [0.75275122 0.00429027 0.03875078]
 [0.71058745 0.16809042 0.04854757]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[2 3 1 0]
[ 0  2  4  6  8 10 12 14 16 18]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[1. 2. 3. 4. 5. 6. 7.]
[0.   0.25 0.5  0.75 1.  ]


**Tipos de datos**

Una matriz es una colección de elementos del mismo tipo de datos y NumPy admite y proporciona funciones integradas para construir matrices con argumentos opcionales para especificar explícitamente los tipos de datos requeridos.

In [3]:
# Numpy escoge el tipo de datos
x = np.array([0, 1])  
y = np.array([2.0, 3.0])  

# Fuerza un tipo de datos en particular
z = np.array([5, 6], dtype=np.int64)  
print (x.dtype, y.dtype, z.dtype)

### Ejercicio Completa el siguiente código
import numpy as np

np.random.seed(0)

x1 = np.random.randint(10, size=6)  # matriz 1-d
x2 = np.random.randint(10, size=(3, 4))  # matriz 2-d
x3 = np.random.randint(10, size=(3, 4, 5)) # matriz 3-d

# Imprime los atributos: dim, shape, size, dtype, itemsize y nbytes
print("x1:")
print("Dimension:", x1.ndim)
print("Shape:", x1.shape)
print("Size:", x1.size)
print("Dtype:", x1.dtype)
print("Itemsize:", x1.itemsize, "bytes")
print("Nbytes:", x1.nbytes, "bytes")

print("\nx2:")
print("Dimension:", x2.ndim)
print("Shape:", x2.shape)
print("Size:", x2.size)
print("Dtype:", x2.dtype)
print("Itemsize:", x2.itemsize, "bytes")
print("Nbytes:", x2.nbytes, "bytes")

print("\nx3:")
print("Dimension:", x3.ndim)
print("Shape:", x3.shape)
print("Size:", x3.size)
print("Dtype:", x3.dtype)
print("Itemsize:", x3.itemsize, "bytes")
print("Nbytes:", x3.nbytes, "bytes")


int64 float64 int64
x1:
Dimension: 1
Shape: (6,)
Size: 6
Dtype: int64
Itemsize: 8 bytes
Nbytes: 48 bytes

x2:
Dimension: 2
Shape: (3, 4)
Size: 12
Dtype: int64
Itemsize: 8 bytes
Nbytes: 96 bytes

x3:
Dimension: 3
Shape: (3, 4, 5)
Size: 60
Dtype: int64
Itemsize: 8 bytes
Nbytes: 480 bytes


**Indexación de matrices**