<a href="https://colab.research.google.com/github/Gilmar-PY/C8280AC2/blob/main/Actividad2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Matrices**                     
Una matriz NumPy es una colección de valores de tipos de datos similares y está indexada por una tupla de números no negativos. El rango de la matriz es el número de dimensiones, y la forma de una matriz es una tupla de números que dan el tamaño de la matriz a lo largo de cada dimensión

In [1]:
# Ejemplo 
from __future__ import division
import time
import numpy as np
tam_vec = 1000
def lista_python():
    t1 = time.time()
    X = range(tam_vec)
    Y = range(tam_vec)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1
def matriz_numpy():
    t1 = time.time()
    X = np.arange(tam_vec)
    Y = np.arange(tam_vec)
    Z = X + Y
    return time.time() - t1
# Completar
import numpy
print(numpy.__version__)



1.22.4


Podemos inicializar matrices NumPy a partir de listas de Python anidadas y acceder a los elementos mediante corchetes.

In [2]:
import numpy as np

# Creamos una matriz 3x3 de todos ceros
a = np.zeros((3,3)) 
print(a)

# Creamos una matriz 2x2 de todos 1
b = np.ones((2,2))  
print(b)

# Creamos una matriz 3x3 constantes
c = np.full((3,3), 7)
print(c)

# Creamos una matriz 3x3 con valores aleatorios
d = np.random.random((3,3)) 
print(d)

# Creamos una matriz identidad 3x3 
e = np.eye(3)
print(e)

# Convertir una lista en una matriz 
f = np.array([2, 3, 1,0])
print(f)

# arange() crea matrices con valores que se incrementan regularmente
g = np.arange(0, 20, 2) # Del 0 al 20 con incremento de 2
print(g)

# Mezcla de tupla y listas
h = np.array([(1.5,2,3), (4,5,6)]) # Crea una matriz de 2x3
print(h)

# Crear una matriz de rango con tipo de datos flotante
i = np.arange(1, 8, dtype=np.float64)
print(i)

# linspace() crea matrices con un numero especifico de elementos que están espaciados por igual entre los valores inicial y final especificados
j = np.linspace(0, 1, num=5) # Genera 5 números igualmente espaciados entre 0 y 1
print(j)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.87599492 0.17936402 0.37915184]
 [0.75275122 0.00429027 0.03875078]
 [0.71058745 0.16809042 0.04854757]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[2 3 1 0]
[ 0  2  4  6  8 10 12 14 16 18]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[1. 2. 3. 4. 5. 6. 7.]
[0.   0.25 0.5  0.75 1.  ]


**Tipos de datos**

Una matriz es una colección de elementos del mismo tipo de datos y NumPy admite y proporciona funciones integradas para construir matrices con argumentos opcionales para especificar explícitamente los tipos de datos requeridos.

In [3]:
# Numpy escoge el tipo de datos
x = np.array([0, 1])  
y = np.array([2.0, 3.0])  

# Fuerza un tipo de datos en particular
z = np.array([5, 6], dtype=np.int64)  
print (x.dtype, y.dtype, z.dtype)

### Ejercicio Completa el siguiente código
import numpy as np

np.random.seed(0)

x1 = np.random.randint(10, size=6)  # matriz 1-d
x2 = np.random.randint(10, size=(3, 4))  # matriz 2-d
x3 = np.random.randint(10, size=(3, 4, 5)) # matriz 3-d

# Imprime los atributos: dim, shape, size, dtype, itemsize y nbytes
print("x1:")
print("Dimension:", x1.ndim)
print("Shape:", x1.shape)
print("Size:", x1.size)
print("Dtype:", x1.dtype)
print("Itemsize:", x1.itemsize, "bytes")
print("Nbytes:", x1.nbytes, "bytes")

print("\nx2:")
print("Dimension:", x2.ndim)
print("Shape:", x2.shape)
print("Size:", x2.size)
print("Dtype:", x2.dtype)
print("Itemsize:", x2.itemsize, "bytes")
print("Nbytes:", x2.nbytes, "bytes")

print("\nx3:")
print("Dimension:", x3.ndim)
print("Shape:", x3.shape)
print("Size:", x3.size)
print("Dtype:", x3.dtype)
print("Itemsize:", x3.itemsize, "bytes")
print("Nbytes:", x3.nbytes, "bytes")


int64 float64 int64
x1:
Dimension: 1
Shape: (6,)
Size: 6
Dtype: int64
Itemsize: 8 bytes
Nbytes: 48 bytes

x2:
Dimension: 2
Shape: (3, 4)
Size: 12
Dtype: int64
Itemsize: 8 bytes
Nbytes: 96 bytes

x3:
Dimension: 3
Shape: (3, 4, 5)
Size: 60
Dtype: int64
Itemsize: 8 bytes
Nbytes: 480 bytes


**Indexación de matrices**

**Acceso al campo**

In [2]:
import numpy as np

x = np.array([5, 6, 7, 8, 9])

# Utilizando pasos de 2
print(x[1:7:2])

# Usando índices negativos
print(x[-2:5]) 
print(x[-1:1:-1])

# Si no se proporciona un inicio de rango, se toma el valor predeterminado como 0 para pasos positivos, y n-1 para pasos negativos
print(x[4:]) # Selecciona todos los elementos desde el cuarto índice hasta el final

# Usando elipsis
x2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x2[...,0])  # Esto seleccionará todos los elementos en el primer índice del segundo eje (o sea, la primera columna)



[6 8]
[8 9]
[9 8 7]
[9]
[1 4 7]


**Ejercicio**

Crea una matriz de rango 2 con dimension (3, 4)
Usa el recorte para extraer la submatriz que consta de las primeras 2 filas y las columnas 1 y 2.
Una parte de una matriz es solo una vista de los mismos datos, comprueba quecualquier modificación modificará la matriz original.

In [3]:
import numpy as np
# Crea una matriz de rango 2 con dimension (3, 4)
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Usa el recorte para extraer la submatriz que consta de las primeras 2 filas y las columnas 1 y 2.
sub_matriz = x[:2, 1:3]
print("Submatriz:")
print(sub_matriz)

sub_matriz[0, 0] = 50 # modificamos el primer elemento de la submatriz

print("\nMatriz original tras modificar la submatriz:")
print(x)


Submatriz:
[[2 3]
 [6 7]]

Matriz original tras modificar la submatriz:
[[ 1 50  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Indexación avanzada**

In [4]:
import numpy as np

# Creamos una matriz
a = np.array([[1,2], [3, 4]])
# Indexación avanzada
print(a[[0, 1], [0, 1]])
print(np.array([a[0, 0], a[1, 1]]))
print(a[[0, 0], [1, 1]])
print(np.array([a[0, 1], a[0, 1]]))


[1 4]
[1 4]
[2 2]
[2 2]


In [5]:
import numpy as np

# Creamos una matriz
a = np.array([[1,2], [3, 4]])
# Indexación avanzada
print(a[[0, 1], [0, 1]])
print(np.array([a[0, 0], a[1, 1]]))
# Al usar la indexación de un matriz se reutiliza el mismo elemento de la matriz de origen:
print(a[[0, 0], [1, 1]])
print(np.array([a[0, 1], a[0, 1]]))

# Reshaping
x4 = np.arange(1, 10).reshape((3, 3))
print(x4)

# Conversión de una matriz unidimensional en una fila o columna de una matriz bidimensional
x5 = np.array([1, 2, 3])
# vector fila via reshape
x5_row = x5.reshape((1, 3))
print(x5_row)

# vector fila con newaxis
x5_row_newaxis = x5[np.newaxis, :]
print(x5_row_newaxis)

# vector columna via reshape
x5_col = x5.reshape((3, 1))
print(x5_col)

# vector columna con newaxis
x5_col_newaxis = x5[:, np.newaxis]
print(x5_col_newaxis)


[1 4]
[1 4]
[2 2]
[2 2]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]]
[[1 2 3]]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


**Concatenación y separación**

In [7]:
import numpy as np
x = np.array([4, 5, 6])
y = np.array([7, 8, 9])
print(np.concatenate([x, y]))

# concatenacion de dos o mas matrices
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

# concatendo una matriz dos veces
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(np.concatenate([grid, grid]))

# Para matrices de distintas dimensiones, se usan las funciones vstack y hstack:
x = np.array([0, 1, 2])
grid = np.array([[3, 4, 5],
                 [6, 5, 4]])

# Se junta la matriz de manera vertical
print(np.vstack([x, grid]))

# Se junta la matriz de manera horizontal
y = np.array([[23],
              [23]])
print(np.hstack([grid, y]))

# División o separación de matrices
x = [1, 2, 3, 44, 95, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

# Fancy indexing
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
print(x)

# Accedemos a tres elementos diferentes
indices = [1, 5, 2]
print(x[indices])

# Trabajar en múltiples dimensiones
X = np.arange(12).reshape((3, 4))
print(X)

row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
print(X[row, col])

# Broadcasting
print(row[:, np.newaxis] * col)

# Combinando indexado fancy y indices simples
print(X[2, [2, 0, 1]])

# Combinando indexado fancy y el recorte
print(X[1:, [2, 0, 1]])

# Modificando partes de una matriz con fancy indexing
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

# Operación inesperada con índices repetidos
x = np.zeros(10)
x[[0, 0]] = [4, 6]
print(x)

i = [2, 3, 3, 4, 4, 4]
x[i] += 1
print(x)

# Método at() de ufuncs
x = np.zeros(10)
np.add.at(x, i, 1)
print(x)


[4 5 6 7 8 9]
[ 4  5  6  7  8  9 99 99 99]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[0 1 2]
 [3 4 5]
 [6 5 4]]
[[ 3  4  5 23]
 [ 6  5  4 23]]
[1 2 3] [44 95] [3 2 1]
[51 92 14 71 60 20 82 86 74 74]
[92 20 14]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 2  5 11]
[[0 0 0]
 [2 1 3]
 [4 2 6]]
[10  8  9]
[[ 6  4  5]
 [10  8  9]]
[ 0 99 99  3 99  5  6  7 99  9]
[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[6. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
[0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]


Expresiones vectorizadas

Agregaciones 

In [9]:
import numpy as np

# Generamos 100 números aleatorios
L = np.random.random(100)

# Sumamos todos los números generados
print(sum(L))

# Usando np.sum para realizar la suma
print(np.sum(L))

# Creando una matriz grande de números aleatorios
matriz_grande = np.random.rand(1000000)

# Usando la función de sum de Python
%timeit sum(matriz_grande)

# Usando np.sum
%timeit np.sum(matriz_grande)

# Probando las funciones min y max de Python
print(min(matriz_grande), max(matriz_grande))

# Cronometrando las funciones min y max de Python
%timeit min(matriz_grande)
%timeit max(matriz_grande)

# Cronometrando np.min y np.max
%timeit np.min(matriz_grande)
%timeit np.max(matriz_grande)

# Generando una matriz de números aleatorios con una distribución normal
data = np.random.normal(size=(15, 15))

# Calculando la media de los datos
print(np.mean(data))

# Usando el método mean de la clase ndarray
print(data.mean())

# Creando una matriz M
M = np.random.random((5, 6))
print(M)

# Sumando todos los elementos de M
print(M.sum())

# Sumando los elementos de cada columna de M (axis=0)
print(M.sum(axis=0))

# Creando una matriz 3D
data = np.random.normal(size=(5, 10, 15))

# Comprobando las dimensiones al sumar sobre el primer eje (axis=0)
print(data.sum(axis=0).shape)

# Comprobando las dimensiones al sumar sobre el primer y último eje (axis=(0, 2))
print(data.sum(axis=(0, 2)).shape)

# Sumando todos los elementos de la matriz
print(data.sum())


51.91480529344025
51.914805293440246
90.5 ms ± 3.08 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
573 µs ± 209 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
3.0185099157975515e-06 0.9999984248234998
62.8 ms ± 1.15 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
83.7 ms ± 25.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
455 µs ± 17.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
441 µs ± 10.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
-0.043423813956152
-0.043423813956152
[[0.48005443 0.31120198 0.72355208 0.96661499 0.11794458 0.71913579]
 [0.07398183 0.69626344 0.21234385 0.13067606 0.34539405 0.68547342]
 [0.09437749 0.1497619  0.37090778 0.69389464 0.33574342 0.45128571]
 [0.57578883 0.10488456 0.38265104 0.65051719 0.15449987 0.58861723]
 [0.63646935 0.81813214 0.28398329 0.69724557 0.21607515 0.62769829]]
13.295169952347251
[1.86067195 2.08024402 1.97343803 3.13894844 1.16965708 3.07221044]
(10, 15)
(10,)
4.22939

**Broadcasting**

In [ ]:
# 1. Crear una matriz 3D
A = np.ones((3, 3, 3))
print("A:")
print(A)

# 2. Crear una matriz 1D
B = np.array([1, 2, 3])
print("\nB:")
print(B)

# 3. Usar broadcasting para agregar B a cada "nivel" de A
C = A + B[:, np.newaxis]
print("\nC:")
print(C)

# 4. Usar broadcasting para agregar B a cada fila de cada "nivel" de A
D = A + B
print("\nD:")
print(D)


**Regla del broadcasting**

El broadcasting en NumPy sigue un estricto conjunto de reglas para determinar la interacción entre dos matrices :

Regla 1: Si las dos matrices difieren en su número de dimensiones, la forma de la matriz que tiene menos dimensiones se rellena con unos en el lado principal (izquierdo).

Regla 2: Si la forma de los dos matrices no coincide con ninguna dimensión, la matriz con la forma igual a 1 en esa dimensión se estira para que coincida con la otra dimensión.

Regla 3: Si en cualquier dimensión los tamaños son distintos y ninguno es igual a 1, se genera un error.

In [11]:
# Un útil truco:
J = np.arange(0, 40, 10)
print(J.shape)
J = J[:, np.newaxis]  # agregamos un nuevo eje -> matriz 2D
print(J.shape)
print(J)
print(J + 3)

# Comparaciones, máscaras y lógica Booleana
a1 = np.array([1, 2, 3, 4])
b1 = np.array([4, 3, 2, 1])
print(a1 < b1)
print(np.all(a1 < b1))
print(np.any(a1 < b1))
if np.all(a1 < b1):
    print(" Todos los elementos en a1 son menores que los elementos en b1 ")
elif np.any(a1 < b1):
    print("Algunos elementos en a1 son menores que los elementos de b1")
else:
    print("Todos los elementos en b1 son menores que los elementos de a1")

# Al aparecer en una expresión aritmética junto con un número escalar, u otra matriz NumPy con un tipo de datos numéricos, 
# una matriz booleana se convierte en una matriz numérica con valores 0 y 1 en lugar de False y True, respectivamente.
# Crear una matriz booleana
bool_array = a1 < b1
print("Matriz booleana: ", bool_array)

# uso de la matriz booleana 
num_array = bool_array * 10
print("Matriz numérica: ", num_array)

#  Esta es una propiedad útil para la computación condicional, como cuando se definen funciones

def pulso(t, posicion, altura, ancho):
    return altura * (t >= posicion) * (t <= (posicion + ancho))

t = np.linspace(0, 1, 100)  # rango de valores de tiempo
y = pulso(t, posicion=0.4, altura=1, ancho=0.2)  # Calcula el pulso en estos tiempos

print(y)


(4,)
(4, 1)
[[ 0]
 [10]
 [20]
 [30]]
[[ 3]
 [13]
 [23]
 [33]]
[ True  True False False]
False
True
Algunos elementos en a1 son menores que los elementos de b1
Matriz booleana:  [ True  True False False]
Matriz numérica:  [10 10  0  0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


**Matrices booleanas como máscaras**

In [12]:
# masked array
k = np.array([1, 3, -1, 5, 7, -1])
mask = (k < 0)
print(mask)

# Un ejemplo bidimensional
rng = np.random.RandomState(0)
z1 = rng.randint(10, size=(3, 4))
print(z1)

# Crear una máscara para valores mayores que 5
mask = z1 > 5
print(mask)

# Ahora, para seleccionar estos valores de la matriz, podemos simplemente indexar en esta matriz booleana,
# esto se conoce como una operación de enmascaramiento:

# Aplicar la máscara
print(z1[mask])
# El siguiente ejemplo muestra cómo sumar la matriz de enmascaramiento, donde True representa uno y False representa 0.
# Suma de máscara
print(mask.sum())


[False False  True False False  True]
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[[False False False False]
 [ True  True False False]
 [False False  True  True]]
[7 9 7 6]
4
